#!/bin/sh
TMP=/tmp/.e2webserv

if [ -f /mnt/config/usercmd.sh ]; then
	sed -i '/^exit/i/var/swap/bin/e2webserv -b -c /var/swap/etc/e2webserv.conf' /mnt/config/usercmd.sh
fi

if [ ! -e /var/swap/etc/e2webserv.conf ]; then
	echo "use TPK config file"
	mv /var/swap/etc/e2webserv.conf.e2 /var/swap/etc/e2webserv.conf
	chmod -x /var/swap/etc/e2webserv.conf
else
	echo "found user config file"
	echo "skip TPK config file: e2webserv.conf.e2"
fi

echo "successfully installed"

link=`readlink /var/swap`
if [ `df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1 | wc -l` -eq 1 ] && [ $link = "/mnt/swapextensions" ]; then
	SPACE=`df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1`
	FREE=`expr $SPACE - 100`
	echo "new free space size $FREE kb"
else
	echo "syncing disk"
	sync
fi

echo "start e2webserv..."
/var/swap/bin/e2webserv -b -c /var/swap/etc/e2webserv.conf > /dev/null 2>&1
echo "done."

exit 0