#!/bin/sh
TMP=/tmp/.e2webserv

rm -f /var/swap/bin/e2webserv

if [ -f /mnt/config/usercmd.sh ]; then
	sed -i '/^\/var\/swap\/bin\/e2webserv/d' /mnt/config/usercmd.sh
fi

echo "successfully removed"

link=`readlink /var/swap`
if [ `df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1 | wc -l` -eq 1 ] && [ $link = "/mnt/swapextensions" ]; then
	SPACE=`df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1`
	FREE=`expr $SPACE - 100`
	echo new freespace size $FREE kb
else
	echo "syncing disk"
	sync
fi

exit 0
