#!/bin/sh
#
TMP=/tmp/.e2webserv

model=`cat /etc/model`
echo""
echo "Checking your Boxtype...."
echo ""
if [ "$model" = "" ]; then
	echo "Sorry! This Plugin is not available for your $model because it will not work correctly!!!"
	echo "Aborting installation..."
	exit 1
else
	echo "Boxtype: $model OK"
fi

echo "checking swapstick"
if [ ! -d /var/swap/bin/ ]; then
  echo "--------------------------"
	echo "no swapstick found...."
	echo "--------------------------"
	exit 1
fi
echo "swapstick found...."

link=`readlink /var/swap`
if [ `df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1 | wc -l` -eq 1 ] && [ $link = "/mnt/swapextensions" ]; then
	SPACE=`df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1`
	FREE=`expr $SPACE - 100`
	SIZE=288
	echo "checking freespace"
	echo packege size $SIZE kb
	echo freespace size $FREE kb
	if  [ "$FREE" -lt "$SIZE" ]; then
		echo "sorry no freespace left on device"
		exit 1
	else
		echo ok		
	fi
else
	echo "syncing disk"
	sync
fi


echo "kill e2webserv if running"
killall -9 e2webserv > /dev/null 2>&1

echo "install e2webserv ..."

buildgroup=`cat /etc/.buildgroup`
echo "checking OS"	 
if  [ `cat /etc/motd | grep $buildgroup | grep M | grep rev | wc -l` -eq 0 ]; then 	 	 
	echo --------------------------- 	 	 
	echo DONT USE this IPK Package!! 	 	 
	echo --- 	 	 
	echo Only for $buildgroup Image!! 	 	 
	echo --------------------------- 	 	 
	exit 1 	 	 
fi

exit 0
