#!/bin/sh
TMP=/tmp/.e2webserv

echo "kill e2webserv if running"
killall -9 e2webserv > /dev/null 2>&1

if [ ! -e /var/swap/etc/e2webserv.conf.e2 ]; then
	echo "remove TPK config file"
	rm /var/swap/etc/e2webserv.conf
fi

link=`readlink /var/swap`
if [ `df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1 | wc -l` -eq 1 ] && [ $link = "/mnt/swapextensions" ]; then
	SPACE=`df | grep /dev/mtdblock | grep mnt | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1`
	FREE=`expr $SPACE - 100`
	echo "new free space size $FREE kb"
else
	echo "syncing disk"
	sync
fi

echo "removing e2webserv ..."
exit 0
