#!/bin/sh
TMP=/tmp/.e2webserv

if [ -f /mnt/config/usercmd.sh ]; then
	sed -i '/^exit/i/mnt/bin/e2webserv -b -c /mnt/config/e2webserv.conf' /mnt/config/usercmd.sh
fi

if [ ! -e /mnt/config/e2webserv.conf ]; then
	echo "use TPK config file"
	mv /mnt/config/e2webserv.conf.e2 /mnt/config/e2webserv.conf
	chmod -x /mnt/config/e2webserv.conf
else
	echo "found user config file"
	echo "skip TPK config file: e2webserv.conf.e2"
fi

echo "successfully installed"

if [ `df | grep /dev/mtdblock | grep var | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1 | wc -l` -eq 1 ]; then
	SPACE=`df | grep /dev/mtdblock | grep var | sed 's/ \+/ /g' | cut -d ' ' -f4 | head -n1`
	FREE=`expr $SPACE - 100`
	echo "new free space size $FREE kb"
else
	echo "syncing disk"
	sync
fi

echo "start e2webserv..."
/mnt/bin/e2webserv -b -c /mnt/config/e2webserv.conf > /dev/null 2>&1
echo "done."

exit 0